// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Tim Developer",
            "email": "support@unu.ac.id"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login/request-otp": {
            "post": {
                "description": "Mengirimkan kode OTP ke WhatsApp user yang SUDAH terdaftar.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth WhatsApp"
                ],
                "summary": "Request OTP Login (WA)",
                "parameters": [
                    {
                        "description": "Nomor WhatsApp",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RequestOTPReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OTP Terkirim",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Error Validasi",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/login/verify-otp": {
            "post": {
                "description": "Tukar kode OTP dengan Token JWT.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth WhatsApp"
                ],
                "summary": "Verifikasi OTP Login (WA)",
                "parameters": [
                    {
                        "description": "Data Verifikasi",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.VerifyLoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token JWT",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "OTP Salah/Expired",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/register/request-otp": {
            "post": {
                "description": "Mengirimkan kode OTP ke nomor baru untuk pendaftaran.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth WhatsApp"
                ],
                "summary": "Request OTP Register (WA)",
                "parameters": [
                    {
                        "description": "Nomor WhatsApp",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RequestOTPReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OTP Terkirim",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Error (Misal: Nomor sudah ada)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/register/verify-otp": {
            "post": {
                "description": "Verifikasi OTP sekaligus membuat user baru dengan password.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth WhatsApp"
                ],
                "summary": "Verifikasi OTP Register (WA)",
                "parameters": [
                    {
                        "description": "Data Register Lengkap",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.VerifyRegisterReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User Created \u0026 Token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Validasi Gagal",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.RequestOTPReq": {
            "type": "object",
            "properties": {
                "phone": {
                    "type": "string",
                    "example": "08123456789"
                }
            }
        },
        "auth.VerifyLoginReq": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "123456"
                },
                "phone": {
                    "type": "string",
                    "example": "08123456789"
                }
            }
        },
        "auth.VerifyRegisterReq": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "123456"
                },
                "name": {
                    "type": "string",
                    "example": "Budi Santoso"
                },
                "password": {
                    "type": "string",
                    "example": "rahasia123"
                },
                "phone": {
                    "type": "string",
                    "example": "08123456789"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Masukkan token dengan format \"Bearer \u003ctoken_anda\u003e\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Campus Reservation API",
	Description:      "Dokumentasi API untuk Sistem Reservasi Kampus (UniSpace).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
